/*
  Warnings:

  - The values [TRACK_VIEW] on the enum `EventType` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "EventType_new" AS ENUM ('LOGIN', 'LOGOUT', 'CREATE_USER', 'CREATE_PROJECT', 'CREATE_PUBLICATION', 'UPDATE_PUBLICATION', 'DELETE_PUBLICATION', 'CREATE_COMMENT', 'REPLY_COMMENT', 'VIEW_HOME', 'VIEW_STATE', 'VIEW_COMMUNITY', 'VIEW_PUBLICATION', 'VIEW_PROFILE', 'CLICK_PUBLICATION', 'CLICK_STATE', 'CLICK_COMMUNITY', 'CLICK_PROFILE', 'SUBSCRIBE_COMMUNITY', 'UNSUBSCRIBE_COMMUNITY', 'LIKE_PUBLICATION', 'UNLIKE_PUBLICATION', 'SHARE_PUBLICATION', 'BOOKMARK_PUBLICATION', 'UNBOOKMARK_PUBLICATION', 'SEND_MESSAGE', 'READ_MESSAGE', 'VIEW_NOTIFICATION', 'CLICK_NOTIFICATION', 'SEARCH_QUERY', 'VIEW_SEARCH_RESULTS', 'CLICK_SEARCH_RESULT');
ALTER TABLE "Event" ALTER COLUMN "type" TYPE "EventType_new" USING ("type"::text::"EventType_new");
ALTER TYPE "EventType" RENAME TO "EventType_old";
ALTER TYPE "EventType_new" RENAME TO "EventType";
DROP TYPE "EventType_old";
COMMIT;
